### ISSUE TITLE
Odd inefficiency in ec25519.c#L370

### ISSUE THREAD

**Issue by tommythorn** [CRTandKDU/TRS80#1]
In
```
364	/** Adds 1B k to 32B u returning 33B t. Max 10157 T */
365	void add0132_33( unsigned char *t, unsigned char k, unsigned char *u ){
366	  unsigned int carry;
367	  unsigned char i;
368	  carry = 0;
369	  for( i=0; i<32; i++ ){
370	    if( 0==i ){ carry += k; }
371	    carry += u[i];
372	    t[i]  = (carry%256);
373	    carry >>= 8;
374	  }
```

why wasn't carry simply initialized to `k`, making the conditional in line 370 unnecessary?
(Note, I assume that SDCC isn't smart enough to figure this out on its own.)

**Comment by CRTandKDU** [comment]
Indeed you're perfectly right, and there are some other places too in the code where some obvious optimizations are begging (add0232_33 is another example). The objective, however, wasn't to produce optimal code for the platform but simply build a tentative implementation that would actually work on a vintage 16K TRS. The choice of the Comba multiplication rather than faster methods, for instance, could also be discussed.

Since the source was laid to rest in this github, other works were published that are much more interesting if you are into small footprint CPU/controller implementations:
- See: https://eprint.iacr.org/2015/343 by Schwabe and all for fast and modern implementations on microcontrollers;
- AVRNaCl: https://munacl.cryptojedi.org/atmega.shtml is inspiring;
- de Groot's thesis: https://pure.tue.nl/ws/files/47038543/800603-1.pdf

If you're planning to do or doing some work on the TRS 80 (specifically 16K Model I in its bare essentials) I'd be interested to keep in touch, if only out of nostalgia. Thank you for your interest.

CRT_and_KDU

**Comment by tommythorn** [comment]
Thanks for the reply (jmc@massiverand.com didn't work).
I'll look at the pointers, but the interest was specifically Z-80, in the Nascom 2
embodiment (purely for fun and nostalgia).
